apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Release.Name }}-pod
  name: {{ .Release.Name }}-pod
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: {{ .Values.name }}
