apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pod
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: {{ .Release.Name }}-pod 
  type: NodePort
